# Generated by Django 2.2.9 on 2019-12-31 10:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cms', '0022_auto_20180620_1551'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimedContentPlugin',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='timer_timedcontentplugin', serialize=False, to='cms.CMSPlugin')),
                ('timed_start', models.DateTimeField(blank=True, null=True, verbose_name='Visible since')),
                ('timed_end', models.DateTimeField(blank=True, null=True, verbose_name='Visible until')),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
    ]
