# Generated by Django 2.2.9 on 2019-12-31 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='timedcontentplugin',
            name='cta',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='timedcontentplugin',
            name='description',
            field=models.CharField(blank=True, max_length=5000),
        ),
        migrations.AddField(
            model_name='timedcontentplugin',
            name='title',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
